---
title: "CA 2008 Oil Spill Incidents"
author: "Mariano Viz"
date: "20/02/2021"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(janitor)
library(sf)
library(tmap)
library(gstat)
library(stars)

```


**Data source:** 

## Summary

## Read in data, update col names, and check projection

```{r}
#Read in Oil Spill Incident Tracking data and update col names to lowercase:
oil_spill <- read_sf(here("Oil_Spill_Incident_Tracking_%5Bds394%5D-shp"), layer = "Oil_Spill_Incident_Tracking_%5Bds394%5D") %>% 
  clean_names() %>% 
  rename(Location = inlandmari) 

# Check Oil Spill Incident Tracking data projection:
#st_crs(oil_spill) # WGS 84 (EPSG,3857)


# Read in the CA county data, update col names to lowercase, and keep only names:
ca_counties <- read_sf(here("ca_counties"), layer = "CA_Counties_TIGER2016") %>% 
  clean_names() %>% 
  select(name) 

# Check the CA county projection
#st_crs(ca_counties) # WGS 84 (EPSG,3857)

#Same Projection as Oil Spill Incident Tracking data (no need to set or transform CRS)


```


## Exploratory interactive map of oil spill events

```{r}
# Check data with a quick ggplot:
#ggplot() +
  #geom_sf(data = ca_counties) +
  #geom_sf(data = oil_spill, aes(color = Location), size = 0.5)

#Interactive plot (tmap)
tmap_mode("view")

tm_shape(oil_spill) +
  tm_dots("Location") 

```




## Finalized static chloropleth map
Make a finalized static chloropleth map in ggplot in which the fill color for each county depends on the count of inland oil spill events by county for the 2008 oil spill data


```{r}
#Only keep inland oil spills:
inland_oil_spill <- oil_spill %>% 
  filter(Location == "Inland")

#Spatial join of data:
ca_oil_spill <- ca_counties %>%
  st_join(inland_oil_spill)

#Counts of inland oil spills by county:
oil_spill_counts <- ca_oil_spill %>% 
  count(name)
#oil_spill_subset

#Static chloropleth map:
ggplot(data = oil_spill_counts) +
  geom_sf(aes(fill = n), color = "white", size = 0.1) +
  scale_fill_gradientn(colors = c("lightsalmon1","orangered1","red4")) +
  theme_minimal() +
  labs(fill = "Inland oil spills (2008)")

```

















