---
title: "a3_task2_viz_mariano"
author: "Mariano Viz"
date: "20/02/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(raster)
library(tidyverse)
library(here)
library(sf)
library(fasterize)
library(rnaturalearth)
```



```{r}
#Rasterizing all layers together: `raster::stack()`
ca_cet <- raster::stack(list.files(path = "ca_cetaceans", pattern = ".tif", full.names = TRUE))


ca_cet
plot(ca_cet)

```



```{r}
#Convert to data frame:
ca_cet_df <- raster::rasterToPoints(ca_cet) %>%
  as.data.frame()

#Data wrangling:
ca_cet_wrang <- ca_cet_df %>%
  pivot_longer(!1:2,  names_to = "species", values_to = "prob") %>%
  mutate(presence =  case_when(prob >= "0.6" ~ 1,
                               TRUE ~ 0))

#Counts by presence (prob > 0.6):
ca_cet_counts <- ca_cet_wrang %>% 
  group_by(x,y) %>% 
  summarise(counts = sum(presence))

ca_cet_counts

usa_sf <- ne_download(scale = "large", type = 'states', category = 'cultural', returnclass = 'sf')

ggplot() +
  geom_raster(data = ca_cet_counts, aes(x = x, y = y, fill = counts))+
  geom_sf(data = usa_sf)+ 
  coord_sf(xlim = c(-125, -115), ylim = c(32, 38), expand = FALSE) +
  scale_fill_gradientn(colors = c("gray97","skyblue1","dodgerblue4")) +
  theme_minimal() +
  labs(fill = "Cetacean Species counts")




```

**Figure 1.**
